### ISSUE TITLE
Parsing nested objects (not embedded)

### ISSUE THREAD

**Issue by WWind220** [deblockt/hal-rest-client#1]
Is it possible to parse nested objects, nested array, which are not embedded and doesn't have _link and href properties?

**Comment by deblockt** [comment]
Can you provide an example (json response, expected typescript result)?
What do you mean by "parse"? 
Actually, nested objects are just parsed as json object. If nested object have a _link, so it's parse as an HalResource.

**Comment by WWind220** [comment]
Here's an example. 
I'm getting such response from server

```
{
	"_links": {
		"self": {
			"href": "http://localhost:8080/notificationConfig",
			"type": "application/hal+json"
		},
		"updateNotificationConfigs": {
			"href": "http://localhost:8080/notificationConfig/update",
			"type": "application/hal+json"
		}
	},
	"cellphoneSet": false,
	"notificationConfigs": [
		{
			"notificationDescription": "Your password has been reset",
			"category": "Login",
			"subcategory": "Reset_Password",
			"email": {
				"id": 3,
				"enabled": true
			}
		},
		{
			"notificationDescription": "Multi Factor Authentication token email",
			"category": "MultiFactorEmailToken",
			"subcategory": "Token_Emailed",
			"email": {
				"id": 17,
				"enabled": true
			}
		}
	]
}
```
And I'm trying parse it via 
```
 getHalNotification():Promise<HalNotification>{
        return this.http.halClient.fetch("/notificationConfig", HalNotification);
    }
```
Here's my models
```
export class HalNotification extends HalResource {
    public cellphoneSet;
    public notificationConfigs: NotificationConfig[];
}

export class NotificationConfig {
    public category;
    public notificationDescription;
    public subcategory;
    public email: NotificationEmail;

}

export class NotificationEmail {
    public id;
    public enabled;
}
```

And getting an error <b>Error: object is not hal resource</b>

Probably I misunderstood something, but I can't figure out what exactly.

**Comment by deblockt** [comment]
You code seem to be fine. 
I'will looking why you have this error.

**Comment by deblockt** [comment]
Issue is fixed.
Warning: To use HalResource you must use `@HalProperty` to map json to typescript object. If not will not be able to get value with `object.cellphoneSet`.

Exemple : 

``` typescript
class NotificationConfig {
    public category;
    public notificationDescription;
    public subcategory;
    public email: NotificationEmail;
}

class HalNotification extends HalResource {
    @HalProperty()
    public cellphoneSet;

    @HalProperty(NotificationConfig)
    public notificationConfigs: NotificationConfig[];
}

class NotificationEmail {
    public id;
    public enabled;
}
```

You can upgrade to 0.2.1, and this model will work.

**Comment by WWind220** [comment]
Thanks for the fast response an fix. 
I just want to make a note that the order of class declaration is important, because if I'll declare `HalNotification` and after that  `NotificationConfig`, I'll get  
`ZoneAwareError  HalNotification.notificationConfigs for Array you need to specify a type on @HalProperty.Example : @HalProperty(HalResource) or @HalProperty(ClassOfArrayContent)`
in browser console

**Comment by deblockt** [comment]
no problem.

Yes, it's because anotation is executed when the javascript file is readed.
If you declare `HalNotification` before `NotificationConfig`, when `@HalProperty(NotificationConfig)` is evaluated, `NotificationConfig` doesn't exists. So annotation have `undefined` parameter instead of `NotificationConfig`.
