### ISSUE TITLE
collection under props with undefined objects

### ISSUE THREAD

**Issue by baxtheman** [deblockt/hal-rest-client#12]
Hi again,

I've another case to analyze with you.

This is the json returned by spring application: 
[https://gist.github.com/baxtheman/0d954791b339647f9044e2e8640a9f96](https://gist.github.com/baxtheman/0d954791b339647f9044e2e8640a9f96)

Inside every `commessa` master object there is a `lavorazioni` children objects collection. In the gist you find the java definitions also.

From fetch by the hal-rest-client the resource obtained for a `commessa` object is this:

![](https://i.imgur.com/VOb0Kae.jpg)

Then, why the `props.lavorazioni` is an not empty array of undefined object?

**Comment by baxtheman** [comment]
Meanwhile I'm tryng to change the spring json output to have a better format.

Are you able to understand if the json in the gist is HAL compliant?

**Comment by deblockt** [comment]
I think this is your correction proposal on issue #11 you create this issue. 
Have you update your dependencies? Your modification have been removed? 

I have try a subset of your json on my unit test and all worked fine.

**Comment by baxtheman** [comment]
Ok, maybe is what you said. 
I clean the node modules and npm install the last version.

**Comment by baxtheman** [comment]
Yes, it was false issue, thankyou
