### ISSUE TITLE
Is it possible to upload the file during the Resource creation?

### ISSUE THREAD

**Issue by EvgeniyReznichenko** [deblockt/hal-rest-client#16]
Hello,

I'm wondering if it is possible to upload the file during the new Resource creation? e.g:

```
export class Avatar extends HalResource {

    @HalProperty()
    image: any; // <--- expect to handle the file

    @HalProperty()
    name: string;
}
```

On the HTML view lets assume we have something like that

```
<label>UploadAvatar</label>
<input class="form-control" type="file" (change)="onFileInputChange($event)">
```

TS method looks as below:

```
onFileInputChange(event) {
        if(event.target.files.length > 0) {
            let file = event.target.files[0];
            const resource = createResource(this.http.halClient, Avatar, "avatar/");
            resource.image = file;
            resource.name = 'Preview';
            resource.create();
        }
}
```

So this example works and the Ajax call is being made successfully, However the payload is incorrect since image field does not send the File but empty object:
![screenshot_1](https://user-images.githubusercontent.com/1070405/32050575-fbf80220-ba59-11e7-83d4-b7eec500da5a.png)

At the same time if I'll do the same without using hal rest client (via native xhr), the request will be correct! e.g:

```
onFileInputChange1(event) {
        if(event.target.files.length > 0) {
            let formData = new FormData();
            formData.append('image', event.target.files[0]);
            formData.append('name', 'Preview');
            this.upload.sendFiles(this.http.apiUrl + '/avatar/', formData).subscribe((progress) => {
                console.log(progress);
            }, (error) => {
                console.log(error);
            });
        }
}
```

Network log:
![screenshot_2](https://user-images.githubusercontent.com/1070405/32050577-00409888-ba5a-11e7-9888-7529597f85bd.png)

**Comment by deblockt** [comment]
Sorry but `hal-rest-client` is done to manage HALResource.
the` image` field, is not an @HalProperty(), it can not be save with the rest of entity `name` field. 

Hal only manage JSON format and not `FormData`, I don't think that is a good idea. 

your  `/avatar` endpoint is not a rest service.

You can look at this forum https://stackoverflow.com/questions/4083702/posting-a-file-and-associated-data-to-a-restful-webservice-preferably-as-json who have multiple solution to do a restfull service with image upload.
