### ISSUE TITLE
get link type

### ISSUE THREAD

**Issue by Zordaxy** [deblockt/hal-rest-client#17]
Can we get custom fields like type from link?
For example I have following link:
txt: {href: "projects/path_to_file", type: "text/plain"}

And I want to use "type" for "Accept" header. But I can't get it from the link. I tried something like 
file.link("txt").prop("type"), file.link("txt").props , but it doesn't work.

Thanks!

**Comment by deblockt** [comment]
Yes, it’s actually not supported.

I will try to implement this feature soon.

**Comment by deblockt** [comment]
This feature have been added on '0.3.1' version. 
You can now use `file.link("txt").prop("type")` to get your link property.

**Comment by Zordaxy** [comment]
0.3.1 version doesn't have types. Doesn't it work for now? Or I've missed something?

**Comment by deblockt** [comment]
@Zordaxy I have fix the build, can you try with 0.3.2 version

**Comment by Zordaxy** [comment]
Works fine, thanks
