### ISSUE TITLE
building since 0.3.0 broken

### ISSUE THREAD

**Issue by Smolli** [deblockt/hal-rest-client#18]
Updating from `0.2.0` to `0.3.0` breaks the build process. Neither `ng build` nor running webpack after a `ng eject` isn't working anymore. The compiler complains, it cannot find the methods from `HalResource`, etc. It throws an exception like this:

    ERROR in C:/<path>/admin-ui/src/app/app.component.ts (48,46): Property 'link' does not exist on type 'BookingList'.

`BookingList` is of type `HalResource`:

    export class BookingList extends HalResource {
        @HalProperty(Booking)
        bookings: Booking[] = [];
    }

Side note: Navigating in Jetbrains IDE isn't working anymore too.

**Comment by deblockt** [comment]
Have you try to remove your node_modules and re-run an `npm  install`?

I don't have this issue. Property link allways exists on `HalResource`.

Can your app.component.ts (line 48)?

**Comment by Zordaxy** [comment]
I also got "-- hal-rest-client@0.3.0  invalid" while installing process.
After that "dist" folder in hal-rest-client contains only js files. No ts files or files with types.

**Comment by deblockt** [comment]
can you try with `0.3.2` version

**Comment by Smolli** [comment]
I don't know what is different. Maybe deleting the `node_modules` directory helped or another dependency got updated, my particular error isn't showing up anymore.

**Comment by Zordaxy** [comment]
It works now, thanks.
