### ISSUE TITLE
Handling paging info

### ISSUE THREAD

**Issue by Spuu** [deblockt/hal-rest-client#2]
Hello. Any idea how to handle paging information when fetching an array? I mean:
{
  "_embedded": {
    "products": [ { ... } ]
  },
  "_links": { ... },
  **"page": {
    "size": 20,
    "totalElements": 100,
    "totalPages": 5,
    "number": 0
  }**
}

I figured out a workaround for that, but it requires 2 requests (one for fetching an array, one for page info).
Can we do it in one shot?

Thanks.

**Comment by Spuu** [comment]
I think i got this.

export class ProductsArray extends HalResource {
    @HalProperty()
    page: PageResource;

    @HalProperty(ProductResource)
    products: ProductResource[];
}

...seems to be good enough.
Sorry for bothering :-)

**Comment by deblockt** [comment]
What is the method used to fetch the array?
If you use `fetchArray` you can't get paging info.
you can use `fetch` to fetch array through Typescript object like this : 
``` typescript
export class Pagination {
   size: number;
   totalElements: number;
   totalPages: number;
   number: number;
}

export class ProductArray extends HalResource {
   @HalProperty(Product)
   products: Product[];

   @HalProperty()
   page: Pagination;
}

``` 

``` typescript
client.fetch('/products', ProductArray)
```

With this model you can have your Array and your Pagination info in one request.

I am currently reflecting an evolution of `fetchArray` to perform the query without going through a model, but this is quite complicated.
