### ISSUE TITLE
resource.update(), resource.delete() don't work in 0.3.*

### ISSUE THREAD

**Issue by Zordaxy** [deblockt/hal-rest-client#21]
Iresource.update(), resource.delete() don't work in 0.3.*, but there can be also another api.
Issue is related to uri. I think these functions try to use this.uri instead of this.uri.uri

**Comment by deblockt** [comment]
Can you provide error message, stacktrace, and code used?

**Comment by Zordaxy** [comment]
There is no error message, but when I do for example "resource.delete()" where  resource is HalResource, i get DELETE request to root of the project. 
For example resources uri is following:
**_uri: URI {uri: "projects/1", templated: false, fetchedURI: ""}**. Before 0.3.* it was **_uri: "projects/1"**
And i get DELETE request to **"http:...projectRoot/"** where it should be **"http:...projectRoot/projects/1"**

**Comment by deblockt** [comment]
This is because on you URI object `fetchedURI` is empty.

How do you have create your resource object?

**Comment by Zordaxy** [comment]
I call**this.http.halClient.fetchArray('/projects?' + query.toString(), Project)** and use separate element of array.

**Comment by deblockt** [comment]
this problem is related to the new functionality of templated links.
delete use `fetchedURI` to get delete patch. When you fetch an array, this attribute is not initialized. 

I will correct this issue like this : 
    - if the link is templated : 
          - if `fetchedURI` is set, use `fetchedURI`
          - else throw error
   - if the link is not templated use `URI`

**Comment by deblockt** [comment]
can yo utry with 0.3.3

**Comment by Zordaxy** [comment]
Works fine. Thanks!
