### ISSUE TITLE
basic auth header not present

### ISSUE THREAD

**Issue by baxtheman** [deblockt/hal-rest-client#27]
Hi,

Talking about version 0.2.6
I need to have authentication and this is the hal client setup:

```
const options = {
  withCredentials: true,
  auth: {
    username: 'user11',
    password: 'pwd44',
  },
};

const halData = createClient(`${serverUrl}/data`, options);
```
but no authentication header appears in the first request: https://i.imgur.com/YZfK7oe.png

What's wrong?
thx

**Comment by deblockt** [comment]
Hi,

On your screenshot you show an OPTION request. 
`OPTION` requests are send for CORS check. I think that theses requests can not have "Authorization" header. 

I think that your api has an issue. It must not check authentication on OPTION requests.

**Comment by baxtheman** [comment]
Thankyou, I'll check the API side!
