### ISSUE TITLE
Link caching

### ISSUE THREAD

**Issue by faragos** [deblockt/hal-rest-client#29]
Do Links get cached? If yes, why? I would like to show stuff based on if the Link is missing or shown. Is this possible?

**Comment by deblockt** [comment]
Links are cached to avoid multiple useless server call.
cache can be cleaned using 
``` ts
import {resetCache} from 'hal-rest-client';

resetCache();
```

I dont' userstand the functional issue. 
You want show information if link return a 404 error?

**Comment by deblockt** [comment]
Can you try with version `0.5.0`, normally cache refresh problems are fixed.

**Comment by faragos** [comment]
I will update it as soon I get my hands on the same project or a new project that uses HAL. I close the issue for now thank you 👍
