### ISSUE TITLE
Look at original data

### ISSUE THREAD

**Issue by davestewart** [deblockt/hal-rest-client#31]
Is there any way to look at the original data returned from a request?

I just want to dump this out when getting to know the API so I can see what's what, rather than having to iterate through all embeds.

If I try to dump the instance out `JSON.stringify()` complains about circular references.

Unless anyone has a better idea of how to do this?

**Comment by deblockt** [comment]
the original data is not kept in the objects.
So I don't think that you can simply see original data.

But you can use debug console to see your service responses.

**Comment by davestewart** [comment]
OK, thanks

**Comment by davestewart** [comment]
I can decorate the methods or add an interceptor also:

```js
sites.restClient.interceptors.response.use(res => {
  console.log('response:', res.data)
  return res
})
```
