### ISSUE TITLE
Allow HTTP request/response interceptors setup

### ISSUE THREAD

**Issue by EvgeniyReznichenko** [deblockt/hal-rest-client#4]
Hello,

Recently we have faced with the situation when we need some specific logic that must be called on every HTTP request/response

Interceptors layer will fit our purposes as best.
However Angular2 interceptors won't make any effect since you are using Axios HTTP client for the communications.

However Axios also allows to set up HTTP req/resp interceptors:
https://github.com/mzabriskie/axios#interceptors

Is there any chance to allow interceptors configuring during the HAL REST client setup?
e.g.

```
this.halClient = createClient(this.apiUrl);
this.halClient.addHeader('Content-Type', 'application/json');
// Add a request interceptor
this.halClient.interceptors.request.use(function (config) {
    // Do something before request is sent
    return config;
  }, function (error) {
    // Do something with request error
    return Promise.reject(error);
});

// Add a response interceptor
this.halClient.interceptors.response.use(function (response) {
    // Do something with response data
    return response;
  }, function (error) {
    // Do something with response error
    return Promise.reject(error);
});
```

Or similar?

Regards,
Evgeniy

**Comment by deblockt** [comment]
Hello,

feature is done on 0.2.2 version.

Your sample code must work now.

Regards.
Thomas

**Comment by EvgeniyReznichenko** [comment]
Wow, that was fast) Thanks a lot!!

From what i see everything works as expected (including withCredentials issue)

Thanks,
Evgeniy
