### ISSUE TITLE
Bug from upgrade 0.4.1 -> 0.5.0

### ISSUE THREAD

**Issue by csigmanek** [deblockt/hal-rest-client#41]
Backend is sending a response

embedded: {
  signal: {
     mysignal: "test"
  }
},
links: {
  signal: "http://mysignal.de"
}

Hal-Rest-Client is converting it:
links: signal does exist
props.signal: signal is undefined

* this is the most likely reason for that bug. There might be another issue. In version 4.1.0 we do see the property while its missing in >4.1.0
The bug to be solved is: An embedded property does not show up in .props

**Comment by deblockt** [comment]
The lib doesn't work correctly when property have same name on `embedded` and `links`.
It's a known bug.
Maybe it will be fix on another version, but not now.
Sorry
