### ISSUE TITLE
Fetch method does not cast resource to an appropriate type

### ISSUE THREAD

**Issue by EvgeniyReznichenko** [deblockt/hal-rest-client#6]
Hi Thomas,

I've faced with a strange issue:
In my code I retrieve dashboard data as like below:

```
async loadDashboardData(): Promise<DashboardInfo> {
     return await this.http.halClient.fetch("/dashboard", DashboardInfo);
}
```
So according to the documentation I expect to retrieve instance of **DashboardInfo** type as a result.

However, instead i get an object of base **HalResource** type:
![untitled](https://user-images.githubusercontent.com/1070405/26877838-ed761686-4b93-11e7-8caf-4133fc1756ca.png)

In all other cases casting went well. So after some research I've found out interesting thing:

If during the previous requests to API through the halClient I will get a HAL resource with a link to the same **href** equal **"/dashboard"**, then future casting won't  work anymore.

It seems like halClient automatically cast all the Links to the default base HalResource type, which makes impossible future casting through the fetch method as in example above.

Can you please take a look on that?

P.S. In support of my idea - once I remove the "/dashboard" href from my API responces, code above has started to work fine and output DashboardInfo instance instead of HalResource.

Best Regards,
Evgeniy

**Comment by deblockt** [comment]
Hi Evgeniy,

If I understand, you do something like that: 
   - first call to /dashboard and get a HalResource
   - second call to /dashboard and you want a `DashboardInfo `

I thinks this doesn't work because HalClient have a cache for getting resource. you can call `resetCache` method to clear cache before your fetch call.
On your first call the HalResource is put on cache, on seconde call, HalResource is getted from cache, so return is a HalResource insteadof `DashboardInfo`.

The cache is usefull for have only one object for a resourceURI. each `/dashboard` resource are the same Object (same memory address).

I will think about how to correct this problem.

**Comment by EvgeniyReznichenko** [comment]
So below i'll try to explain my workflow:
1) I do request on /spa endpoint which outputs the _/dashboard_ href in one of the links
2) I request /dashboard endpoint and try to cast the output to DashboardInfo type, but it fails

Below is my Network profiling:
![screenshot_1](https://user-images.githubusercontent.com/1070405/26880607-94a38700-4b9d-11e7-9cab-e45b4f643667.png)

> you can call resetCache method to clear cache before your fetch call.
How can I call it? I did not find where it is.

Evgeniy

**Comment by deblockt** [comment]
Hello,

Thanks, i see what's append. 
Pending a correction, you can use `resetCache` before calling fetch

To call `resetCache` do this: 
``` typescript
import {resetCache} from 'hal-rest-client';

resetCache();
```

**Comment by EvgeniyReznichenko** [comment]
Awesome, it works!

Thanks a lot,
Evgeniy

**Comment by EvgeniyReznichenko** [comment]
Just my 2c,

I understand why you did that caching mechanism, however it might be useful to force resource casting to the type provided in **fetch** or **fetchArray** method. 
In my case during the 1st **/spa** call i was not able to set up the model type for my **landing** link, so it was automatically assigned to the base HalResource type.
Clear cache will do the "trick", but i would still prefer either:
1) Force recourse type casting despite the cache
2) Provide an ability to set up model type for the links. - In that case I will be able to explicitly say to cast my **landing** link to **DashboardInfo**, so next time cache won't make any issue for me.

What do you think?

Evgeniy

**Comment by deblockt** [comment]
If you use a model to fetch the "/spa", you can force fetch "/dashboard" with `DashboardInfo` class.

example: 

``` typescript

export class Spa extends HalResource {
   @HalProperty()
   landing: DashboardInfo;
}
```

With this model, landing will be fetch with DashboardInfo on the first call.

For more flexibility, I will rewrite the cache procedure to always use the class specified in the fetch method. But it will probably take a little time.

**Comment by deblockt** [comment]
Issue is fixed.

Your original code must work now.

Regards.
Thomas
