### ISSUE TITLE
New private modificator for  restClient field of HalResource class

### ISSUE THREAD

**Issue by EvgeniyReznichenko** [deblockt/hal-rest-client#7]
It seems that with the new 0.2.4 version the restClient field modificator was changed from protected to private. Is there any chance to get back **protected** restClient?

**Comment by deblockt** [comment]
Sorry, it's a mistake. There are no unit test for this feature.

It's fix on 0.2.5 version.

**Comment by EvgeniyReznichenko** [comment]
As usual, Thanks a lot for the quick fix!
