### ISSUE TITLE
Template links

### ISSUE THREAD

**Issue by vdytynyuk** [deblockt/hal-rest-client#9]
It seems that library doesn't work with parsing template links. Are you going to implement templates support?

**Comment by deblockt** [comment]
It's fine, it's not yed implemented. 
I will do that.
Can you provide an example of what do you expect?

**Comment by vdytynyuk** [comment]
@deblockt 
For instance I receive such template - runs/42/files{/path*} and I want to be able to nicely concatenate some path to the prefix of this link. Is it possible?

**Comment by Smolli** [comment]
@deblockt 
Spring Data for example also provides some URLs that take optional parameters like `/bookings{?projection}`. So if you call the URL, I want to be able to add a value for that parameter. So in the end, the URL looks like `/bookings?projection=excerpt`. Without setting the parameter, the URL should read `/bookings`.
Will you consider this too?

**Comment by deblockt** [comment]
Yes, i will consider that. 
But this breaks the existing functioning of links
I will study this issue.

**Comment by deblockt** [comment]
Templated links are now supported.
When you call `fetch`method you can pass object as argument to set url parameters.
Warning, now `HalResource.uri` is an URI object and not a string (see https://github.com/deblockt/hal-rest-client#from-o2).
